# Generated by Django 3.2.4 on 2023-03-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
