name: PR Title Validator

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize


jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const PR_TITLE = "${{ github.event.pull_request.title }}";
            let regex = /^(BUGFIX|FEATURE|TIDY|ENHANCEMENTS) : .+/;
            if (
            !(
            PR_TITLE.startsWith("BUGFIX") ||
            PR_TITLE.startsWith("FEATURE") ||
            PR_TITLE.startsWith("TIDY") ||
            PR_TITLE.startsWith("ENHANCEMENTS")
            )
            ) {
            console.error("PR Title does not start with ' BUGFIX | FEATURE | TIDY | ENHANCEMENTS' keywords."
            );
            process.exit(1);
            }else if (!regex.test(PR_TITLE)) {
            console.error(
            "PR Title is not in correct format please check Metron Standard PR Title:<Change_Type> : <PR description>"
            );
            process.exit(1);
            }
